behaviors:
  CubeTrack:
    trainer_type: ppo
    hyperparameters:
      batch_size: 32
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.8
        strength: 1.0
    keep_checkpoints: 2
    max_steps: 5000000
    time_horizon: 64
    summary_freq: 10000
    threaded: true


